name: todo_app_1_4
description: "Sample project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  flutter_tts: ^3.6.3
  flutter_local_notifications: ^14.0.0
  http: ^0.13.3
  animations: ^2.0.7
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Uncomment and configure if you add assets
  # assets:
  #   - assets/audio/
  #   - assets/images/
